#!/usr/bin/env python3

import argparse
import glob
import os

from grimoire.genome import Reader
import korflab

## Command line stuff ##

parser = argparse.ArgumentParser(description='de-parlogs initial smallgenes')
parser.add_argument('initdir')
parser.add_argument('builddir')
arg = parser.parse_args()

fasta = f'{arg.builddir}/init.fa'
blast = f'{arg.builddir}/blast.out'
os.system(f'cat {arg.initdir}/*.fa > {fasta}')
os.system(f'makeblastdb -in {fasta} -dbtype nucl')
os.system(f'blastn -db {fasta} -query {fasta} -evalue 1e-20 -outfmt 6 >{blast}')

"""
for fasta in glob.glob(f'{arg.initdir}/*.fa'):
	gff = fasta[:-2] + 'gff3'
	genome = Reader(fasta=fasta, gff=gff)
	chrom = next(genome)
	print(chrom.name, chrom.desc)
"""
